# -*- coding: utf-8 -*-
"""Crop_Disease_M2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RBRbeqxTkjMLxruEkhA7WMqo7E-Fs1P8

# 🌿 Crop Disease Detection — EDA & Preprocessing Pipeline
### Milestone 2 | Combined Notebook

---

**Dataset:** Top Agriculture Crop Disease (Kaggle — kamal01)  
**Total Images:** 13,324 | **Classes:** 17 | **Crops:** Corn, Potato, Rice, Wheat, Sugarcane  

### Table of Contents
**Part A — Exploratory Data Analysis**

**Part B — Preprocessing Pipeline**

---
# PART A — Exploratory Data Analysis
---

## 1. ⚙️ Setup & Imports <a id='1'></a>
"""

# Install required libraries
!pip install -q imagehash Pillow tqdm scikit-learn

import os
import shutil
import hashlib
import random
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import imagehash

from PIL import Image, ImageEnhance, UnidentifiedImageError
from tqdm import tqdm
from collections import defaultdict
from sklearn.model_selection import train_test_split

warnings.filterwarnings('ignore')
random.seed(42)
np.random.seed(42)
plt.rcParams['figure.dpi'] = 120
plt.rcParams['font.size'] = 11
sns.set_style('whitegrid')

print('✅ All libraries imported successfully')

# Re-download dataset from Kaggle
!pip install -q kaggle
from google.colab import files
files.upload()  # upload your kaggle.json here

!mkdir -p ~/.kaggle && cp kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d kamal01/top-agriculture-crop-disease
!unzip -q top-agriculture-crop-disease.zip -d /content/dataset

import os
print(os.listdir('/content/dataset'))

from google.colab import drive
drive.mount('/content/drive')
!cp -r '/content/dataset/Crop Diseases' '/content/drive/MyDrive/CropDisease/raw'

# ─── CONFIGURATION — update paths here if needed ─────────────────────────────
DATASET_PATH = '/content/dataset/Crop Diseases'          # raw dataset
PROCESSED_PATH  = '/content/processed'                         # local working output
DRIVE_SAVE_PATH = '/content/drive/MyDrive/CropDisease/processed'  # permanent Drive destination

TARGET_SIZE    = (224, 224)
TRAIN_RATIO    = 0.80
VAL_RATIO      = 0.10
TEST_RATIO     = 0.10
RANDOM_STATE   = 42
AUG_THRESHOLD  = 600   # classes with fewer training images than this will be augmented
AUG_TARGET     = 700   # target training images per minority class after augmentation
VALID_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.bmp', '.tiff'}
# ─────────────────────────────────────────────────────────────────────────────

# Color palette for crop-level visualizations
crop_colors = {
    'Corn':      '#F4A261',
    'Potato':    '#2A9D8F',
    'Rice':      '#457B9D',
    'Wheat':     '#E9C46A',
    'Sugarcane': '#E76F51'
}

assert os.path.exists(DATASET_PATH), f'❌ Dataset path not found: {DATASET_PATH}'
print(f'✅ Dataset found at: {DATASET_PATH}')
print(f'   Target size  : {TARGET_SIZE}')
print(f'   Split ratio  : {TRAIN_RATIO}/{VAL_RATIO}/{TEST_RATIO}')
print(f'   Random seed  : {RANDOM_STATE}')

"""---
## 2. 📦 Dataset Loading & Class Distribution <a id='2'></a>
"""

# Scan all class folders and build master dataframe
class_folders = sorted([
    f for f in os.listdir(DATASET_PATH)
    if os.path.isdir(os.path.join(DATASET_PATH, f))
])

records = []
for cls in class_folders:
    cls_path = os.path.join(DATASET_PATH, cls)
    files = [f for f in os.listdir(cls_path)
             if os.path.splitext(f.lower())[1] in VALID_EXTENSIONS]
    crop = cls.split('_')[0].replace('__', '')
    for f in files:
        records.append({
            'filepath': os.path.join(cls_path, f),
            'filename': f,
            'class':    cls,
            'crop':     crop
        })

df = pd.DataFrame(records)
print(f'📦 Total images loaded : {len(df)}')
print(f'🌿 Total classes       : {df["class"].nunique()}')
print(f'🌾 Total crops         : {df["crop"].nunique()}')
print('\nImages per class:')
print(df['class'].value_counts().to_string())

# Plot 1: Class Distribution
class_counts = df['class'].value_counts().sort_values(ascending=False)
bar_colors = [crop_colors.get(cls.split('_')[0].replace('__',''), '#888') for cls in class_counts.index]

fig, ax = plt.subplots(figsize=(16, 6))
bars = ax.barh(class_counts.index, class_counts.values, color=bar_colors, edgecolor='white', height=0.7)
for bar, val in zip(bars, class_counts.values):
    ax.text(val + 10, bar.get_y() + bar.get_height()/2, str(val), va='center', fontsize=9)
ax.axvline(class_counts.mean(), color='red', linestyle='--', alpha=0.7, label=f'Mean: {class_counts.mean():.0f}')
patches = [mpatches.Patch(color=v, label=k) for k, v in crop_colors.items()]
ax.legend(handles=patches, loc='lower right', title='Crop')
ax.set_xlabel('Number of Images')
ax.set_title('Class Distribution — All 17 Classes', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('class_distribution.png', bbox_inches='tight')
plt.show()

# Plot 2: Crop-level distribution
crop_counts = df['crop'].value_counts()
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].pie(crop_counts.values, labels=crop_counts.index, autopct='%1.1f%%',
            colors=[crop_colors[c] for c in crop_counts.index],
            startangle=140, wedgeprops=dict(edgecolor='white', linewidth=1.5))
axes[0].set_title('Images by Crop Species', fontweight='bold')

axes[1].bar(crop_counts.index, crop_counts.values,
            color=[crop_colors[c] for c in crop_counts.index], edgecolor='white')
for i, (idx, val) in enumerate(crop_counts.items()):
    axes[1].text(i, val + 20, str(val), ha='center', fontsize=10, fontweight='bold')
axes[1].set_title('Image Count by Crop Species', fontweight='bold')
axes[1].set_ylabel('Number of Images')

plt.suptitle('Crop-Level Distribution', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('crop_distribution.png', bbox_inches='tight')
plt.show()

# Imbalance stats
imbalance_ratio = class_counts.max() / class_counts.min()
print(f'Most populated  : {class_counts.idxmax()} ({class_counts.max()} images)')
print(f'Least populated : {class_counts.idxmin()} ({class_counts.min()} images)')
print(f'Imbalance ratio : {imbalance_ratio:.1f}x')
print(f'Mean/class      : {class_counts.mean():.1f}')
print()
low = class_counts[class_counts < 200]
print(f'⚠️  Classes with < 200 images: {", ".join([f"{c} ({n})" for c, n in low.items()])}')

"""---
## 3. 🖼️ Sample Image Grids per Class <a id='3'></a>
"""

def show_sample_grid(df, class_name, n_cols=4, n_rows=4):
    class_df = df[df['class'] == class_name].sample(
        min(n_cols * n_rows, len(df[df['class'] == class_name])), random_state=42)
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 3, n_rows * 3))
    axes = axes.flatten()
    for i, (_, row) in enumerate(class_df.iterrows()):
        try:
            img = Image.open(row['filepath']).convert('RGB')
            axes[i].imshow(img)
        except:
            axes[i].text(0.5, 0.5, 'Error', ha='center', va='center')
        axes[i].axis('off')
    for j in range(i + 1, len(axes)):
        axes[j].axis('off')
    crop = class_name.split('_')[0].replace('__', '')
    color = crop_colors.get(crop, '#888')
    fig.suptitle(f'{class_name}  ({len(df[df["class"]==class_name])} images)',
                 fontsize=13, fontweight='bold', color=color)
    plt.tight_layout()
    plt.savefig(f'samples_{class_name}.png', bbox_inches='tight')
    plt.show()

print('Displaying sample grids for all 17 classes...')
for cls in class_folders:
    show_sample_grid(df, cls)

"""---
## 4. 📐 Image Size & Resolution Analysis <a id='4'></a>
"""

print('📏 Collecting image dimensions...')
widths, heights, channels_list = [], [], []

for _, row in tqdm(df.iterrows(), total=len(df), desc='Reading sizes'):
    try:
        with Image.open(row['filepath']) as img:
            w, h = img.size
            widths.append(w)
            heights.append(h)
            channels_list.append(len(img.getbands()))
    except:
        widths.append(None); heights.append(None); channels_list.append(None)

df['width']        = widths
df['height']       = heights
df['channels']     = channels_list
df['aspect_ratio'] = df['width'] / df['height']

print(f'Width  — min: {df["width"].min():.0f}, max: {df["width"].max():.0f}, mean: {df["width"].mean():.1f}px')
print(f'Height — min: {df["height"].min():.0f}, max: {df["height"].max():.0f}, mean: {df["height"].mean():.1f}px')

# Plot 3: Width, Height, Aspect Ratio
fig, axes = plt.subplots(1, 3, figsize=(17, 4))

axes[0].hist(df['width'].dropna(), bins=40, color='#457B9D', edgecolor='white', alpha=0.85)
axes[0].axvline(df['width'].mean(), color='red', linestyle='--', label=f"Mean: {df['width'].mean():.0f}px")
axes[0].set_title('Image Width Distribution'); axes[0].set_xlabel('Width (px)'); axes[0].legend()

axes[1].hist(df['height'].dropna(), bins=40, color='#2A9D8F', edgecolor='white', alpha=0.85)
axes[1].axvline(df['height'].mean(), color='red', linestyle='--', label=f"Mean: {df['height'].mean():.0f}px")
axes[1].set_title('Image Height Distribution'); axes[1].set_xlabel('Height (px)'); axes[1].legend()

axes[2].hist(df['aspect_ratio'].dropna(), bins=40, color='#E9C46A', edgecolor='white', alpha=0.85)
axes[2].axvline(1.0, color='purple', linestyle='--', alpha=0.7, label='Square (1.0)')
axes[2].set_title('Aspect Ratio Distribution'); axes[2].set_xlabel('Width / Height'); axes[2].legend()

plt.suptitle('Image Size Analysis', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('image_size_distribution.png', bbox_inches='tight')
plt.show()

# Plot 4: Width vs Height scatter
fig, ax = plt.subplots(figsize=(10, 7))
for crop_name, group in df.groupby('crop'):
    ax.scatter(group['width'], group['height'], alpha=0.15, s=8,
               color=crop_colors.get(crop_name, '#888'), label=crop_name)
ax.axvline(224, color='red', linestyle='--', alpha=0.6, label='Target: 224px')
ax.axhline(224, color='red', linestyle='--', alpha=0.6)
ax.set_xlabel('Width (px)'); ax.set_ylabel('Height (px)')
ax.set_title('Width vs Height (colored by crop)', fontweight='bold')
ax.legend(markerscale=4)
plt.tight_layout()
plt.savefig('resolution_scatter.png', bbox_inches='tight')
plt.show()

# Channel check
non_rgb = df[df['channels'] != 3]
print(f'Channel distribution: {df["channels"].value_counts().to_dict()}')
print(f'Non-RGB images: {len(non_rgb)}')

"""---
## 5. 🎨 Pixel Intensity & Color Analysis <a id='5'></a>
"""

# Per-class mean RGB (sampled)
def compute_mean_rgb(filepaths, sample_size=100, target=(128, 128)):
    sampled = np.random.choice(filepaths, min(sample_size, len(filepaths)), replace=False)
    r_vals, g_vals, b_vals = [], [], []
    for fp in sampled:
        try:
            arr = np.array(Image.open(fp).convert('RGB').resize(target)) / 255.0
            r_vals.append(arr[:,:,0].mean())
            g_vals.append(arr[:,:,1].mean())
            b_vals.append(arr[:,:,2].mean())
        except: continue
    return {'mean_R': np.mean(r_vals), 'mean_G': np.mean(g_vals), 'mean_B': np.mean(b_vals)}

print('Computing per-class mean RGB (100 images/class sample)...')
intensity_records = []
for cls in tqdm(class_folders, desc='Classes'):
    fps = df[df['class'] == cls]['filepath'].tolist()
    stats = compute_mean_rgb(fps)
    stats['class'] = cls
    intensity_records.append(stats)
intensity_df = pd.DataFrame(intensity_records)

# Plot 5: Mean RGB per class
x = np.arange(len(intensity_df)); w = 0.25
fig, ax = plt.subplots(figsize=(16, 5))
ax.bar(x - w, intensity_df['mean_R'], w, label='R', color='#E63946', alpha=0.85)
ax.bar(x,     intensity_df['mean_G'], w, label='G', color='#2A9D8F', alpha=0.85)
ax.bar(x + w, intensity_df['mean_B'], w, label='B', color='#457B9D', alpha=0.85)
ax.set_xticks(x)
ax.set_xticklabels(intensity_df['class'], rotation=45, ha='right', fontsize=8)
ax.set_ylabel('Mean Pixel Intensity (0–1)')
ax.set_title('Mean RGB Pixel Intensity per Class', fontweight='bold')
ax.legend()
plt.tight_layout()
plt.savefig('mean_rgb_per_class.png', bbox_inches='tight')
plt.show()

# Plot 6: Full dataset RGB histogram (500 image sample)
print('Computing full-dataset RGB histogram (500 image sample)...')
sample_fps = df['filepath'].sample(min(500, len(df)), random_state=42).tolist()
all_r, all_g, all_b = [], [], []
for fp in tqdm(sample_fps, desc='Sampling'):
    try:
        img = np.array(Image.open(fp).convert('RGB').resize((128, 128))) / 255.0
        all_r.extend(img[:,:,0].flatten())
        all_g.extend(img[:,:,1].flatten())
        all_b.extend(img[:,:,2].flatten())
    except: continue

fig, ax = plt.subplots(figsize=(10, 4))
bins = np.linspace(0, 1, 60)
ax.hist(all_r, bins=bins, alpha=0.6, color='#E63946', label='Red')
ax.hist(all_g, bins=bins, alpha=0.6, color='#2A9D8F', label='Green')
ax.hist(all_b, bins=bins, alpha=0.6, color='#457B9D', label='Blue')
ax.set_xlabel('Pixel Intensity (0–1)'); ax.set_ylabel('Frequency')
ax.set_title('Full Dataset RGB Pixel Intensity Histogram', fontweight='bold')
ax.legend()
plt.tight_layout()
plt.savefig('rgb_histogram.png', bbox_inches='tight')
plt.show()

print(f'R — mean: {np.mean(all_r):.4f}, std: {np.std(all_r):.4f}')
print(f'G — mean: {np.mean(all_g):.4f}, std: {np.std(all_g):.4f}')
print(f'B — mean: {np.mean(all_b):.4f}, std: {np.std(all_b):.4f}')

# Plot 7: Average image per crop (visual fingerprint)
print('Computing average image per crop...')
fig, axes = plt.subplots(1, len(crop_colors), figsize=(16, 3.5))
for ax, (crop_name, color) in zip(axes, crop_colors.items()):
    fps = df[df['crop'] == crop_name]['filepath'].sample(
        min(150, len(df[df['crop'] == crop_name])), random_state=42).tolist()
    avg = np.zeros((128, 128, 3)); count = 0
    for fp in fps:
        try:
            avg += np.array(Image.open(fp).convert('RGB').resize((128,128))) / 255.0
            count += 1
        except: continue
    if count > 0: ax.imshow(avg / count)
    ax.set_title(crop_name, fontweight='bold', color=color); ax.axis('off')
plt.suptitle('Average Image per Crop (Visual Fingerprint)', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('average_image_per_crop.png', bbox_inches='tight')
plt.show()

"""---
## 6. 🔍 Duplicate & Corrupt Image Check <a id='6'></a>
"""

# Corrupt file check
print('Scanning for corrupt images...')
corrupt_files = []
for _, row in tqdm(df.iterrows(), total=len(df), desc='Verifying'):
    try:
        with Image.open(row['filepath']) as img:
            img.verify()
    except Exception as e:
        corrupt_files.append({'filepath': row['filepath'], 'class': row['class'], 'error': str(e)})

print(f'Corrupt files found: {len(corrupt_files)}')
if not corrupt_files:
    print('✅ No corrupt images detected!')

# MD5 exact duplicate check
print('Scanning for exact duplicates (MD5)...')
def md5_hash(fp):
    try:
        with open(fp, 'rb') as f: return hashlib.md5(f.read()).hexdigest()
    except: return None

df['md5_hash'] = [md5_hash(fp) for fp in tqdm(df['filepath'], desc='Hashing')]
dup_mask = df.duplicated(subset='md5_hash', keep=False) & df['md5_hash'].notna()
duplicates_df = df[dup_mask].sort_values('md5_hash')
print(f'Exact duplicate images : {len(duplicates_df)}')
if duplicates_df.empty:
    print('✅ No exact duplicates found!')

# pHash near-duplicate check (500 image sample for EDA)
print('Scanning for near-duplicates (pHash, 500-image sample)...')
sample_df = df.sample(min(500, len(df)), random_state=42)
phashes_eda = {}
for _, row in tqdm(sample_df.iterrows(), total=len(sample_df), desc='pHashing'):
    try:
        phashes_eda[row['filepath']] = imagehash.phash(Image.open(row['filepath']).convert('RGB'))
    except: pass

near_dupes_eda = []
fps_list = list(phashes_eda.keys())
for i in range(len(fps_list)):
    for j in range(i + 1, len(fps_list)):
        if phashes_eda[fps_list[i]] - phashes_eda[fps_list[j]] <= 5:
            near_dupes_eda.append((fps_list[i], fps_list[j]))

print(f'Near-duplicate pairs (from sample): {len(near_dupes_eda)}')
if near_dupes_eda:
    for a, b in near_dupes_eda:
        print(f'  {os.path.basename(a)}  ↔  {os.path.basename(b)}')
print('\n→ Full near-duplicate removal will be performed in Part B preprocessing.')

"""---
## 7. 📋 EDA Summary & Findings <a id='7'></a>
"""

print('=' * 65)
print('      EDA SUMMARY — CROP DISEASE DETECTION DATASET')
print('=' * 65)
print(f'''
DATASET OVERVIEW
   Total images       : {len(df)}
   Total classes      : {df['class'].nunique()}
   Total crops        : {df['crop'].nunique()}

CLASS DISTRIBUTION
   Most images        : {class_counts.idxmax()} ({class_counts.max()} images)
   Fewest images      : {class_counts.idxmin()} ({class_counts.min()} images)
   Imbalance ratio    : {class_counts.max() / class_counts.min():.1f}x
   ⚠️  Sugarcane classes (100 images each) — severe imbalance

IMAGE DIMENSIONS
   Width  : min={df['width'].min():.0f}, max={df['width'].max():.0f}, mean={df['width'].mean():.1f}px
   Height : min={df['height'].min():.0f}, max={df['height'].max():.0f}, mean={df['height'].mean():.1f}px
   → Resize to 224×224 required

COLOR & CHANNELS
   Non-RGB images     : {len(df[df['channels'] != 3])}
   Green channel dominant in healthy leaves — confirmed per class

DATA QUALITY
   Corrupt images     : {len(corrupt_files)}
   Exact duplicates   : {len(duplicates_df)}
   Near-duplicates    : {len(near_dupes_eda)} pairs (500-image sample)
''')
print('=' * 65)
print('''
PREPROCESSING PLAN (executed in Part B below):
   1. Full near-duplicate removal (pHash on entire dataset)
   2. Resize all images → 224×224 (LANCZOS)
   3. RGB conversion (safety step)
   4. Stratified 80/10/10 train/val/test split
   5. Augmentation on minority classes (flip, rotate, brightness,
      contrast, saturation, zoom) → target ~700 training images
   6. Normalisation: ImageNet mean/std at model load time
   7. Save to ImageFolder structure on Google Drive
''')
print('=' * 65)

"""---
# PART B — Preprocessing Pipeline
---
> All variables (`df`, `class_folders`, `crop_colors`, etc.) carry forward directly from Part A. No re-scanning needed.

---
## 8. 🔍 Near-Duplicate Removal (Full Dataset) <a id='8'></a>

EDA sampled 500 images and found near-duplicates. Here we run pHash on the **full dataset** and remove all near-duplicate images before any splitting, to prevent data leakage between train and test.
"""

# Step 1: Remove exact duplicates first
print('Step 1 — Removing exact duplicates (MD5)...')
before = len(df)
df = df.drop_duplicates(subset='md5_hash', keep='first').reset_index(drop=True)
print(f'   Removed : {before - len(df)} exact duplicates')
print(f'   Remaining: {len(df)} images')

# Step 2: Full-dataset pHash near-duplicate removal
print('Step 2 — Full pHash near-duplicate removal...')
print('   (This may take 5–10 minutes)')

phash_map = {}
for fp in tqdm(df['filepath'], desc='pHashing all images'):
    try:
        phash_map[fp] = imagehash.phash(Image.open(fp).convert('RGB'))
    except:
        phash_map[fp] = None

fps_all = list(phash_map.keys())
to_remove = set()
removed_pairs = []

for i in tqdm(range(len(fps_all)), desc='Comparing hashes'):
    if fps_all[i] in to_remove or phash_map[fps_all[i]] is None:
        continue
    for j in range(i + 1, len(fps_all)):
        if fps_all[j] in to_remove or phash_map[fps_all[j]] is None:
            continue
        if phash_map[fps_all[i]] - phash_map[fps_all[j]] <= 5:
            to_remove.add(fps_all[j])
            removed_pairs.append((os.path.basename(fps_all[i]), os.path.basename(fps_all[j])))

before = len(df)
df = df[~df['filepath'].isin(to_remove)].reset_index(drop=True)
print(f'\n   Near-duplicate pairs found  : {len(removed_pairs)}')
print(f'   Images removed              : {before - len(df)}')
print(f'   Images remaining            : {len(df)}')
for a, b in removed_pairs:
    print(f'   KEPT: {a}  |  REMOVED: {b}')

"""---
## 9. 🖼️ Resize & RGB Conversion <a id='9'></a>

**Why 224×224:** Images range from 16px to 6,000px. All CNN architectures require a fixed uniform input size. 224×224 is the ImageNet standard, directly compatible with ResNet, EfficientNet, VGG, and MobileNet pretrained weights.

**Why LANCZOS:** Highest quality resampling filter for downscaling — preserves fine leaf texture detail better than bilinear or nearest-neighbour.
"""

TEMP_RESIZED = '/content/resized_temp'
os.makedirs(TEMP_RESIZED, exist_ok=True)
resize_errors = []
resized_records = []

print(f'Resizing all {len(df)} images to {TARGET_SIZE} and converting to RGB...')

for _, row in tqdm(df.iterrows(), total=len(df), desc='Resizing'):
    try:
        img = Image.open(row['filepath']).convert('RGB').resize(TARGET_SIZE, Image.LANCZOS)
        out_dir = os.path.join(TEMP_RESIZED, row['class'])
        os.makedirs(out_dir, exist_ok=True)
        # Keep original extension name but save as JPEG
        out_fname = os.path.splitext(row['filename'])[0] + '.jpg'
        out_path  = os.path.join(out_dir, out_fname)
        img.save(out_path, 'JPEG', quality=95)
        resized_records.append({'filepath': out_path, 'filename': out_fname,
                                 'class': row['class'], 'crop': row['crop']})
    except Exception as e:
        resize_errors.append({'file': row['filepath'], 'error': str(e)})

df_resized = pd.DataFrame(resized_records)
print(f'\n✅ Resize complete.')
print(f'   Successfully resized : {len(df_resized)}')
print(f'   Errors (skipped)     : {len(resize_errors)}')

# Quick visual verification
sample = df_resized.sample(3, random_state=42)
fig, axes = plt.subplots(1, 3, figsize=(10, 3.5))
for ax, (_, row) in zip(axes, sample.iterrows()):
    img = Image.open(row['filepath'])
    ax.imshow(img)
    ax.set_title(f"{row['class']}\n{img.size}", fontsize=7)
    ax.axis('off')
plt.suptitle('Sample Resized Images (all should show (224, 224))', fontsize=10)
plt.tight_layout()
plt.show()

"""---
## 10. ✂️ Stratified Train / Val / Test Split <a id='10'></a>

**Why stratified:** A plain random split risks placing all 100 Sugarcane images into training, leaving val and test with zero Sugarcane samples. Stratified splitting guarantees every class is proportionally represented in all three splits.
"""

X = df_resized['filepath'].values
y = df_resized['class'].values

# Stage 1: 80% train, 20% temp
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=(VAL_RATIO + TEST_RATIO), stratify=y, random_state=RANDOM_STATE)

# Stage 2: split temp 50/50 into val and test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=RANDOM_STATE)

splits = {
    'train': list(zip(X_train, y_train)),
    'val':   list(zip(X_val,   y_val)),
    'test':  list(zip(X_test,  y_test))
}

print(f'Train : {len(X_train)} images')
print(f'Val   : {len(X_val)} images')
print(f'Test  : {len(X_test)} images')

# Visualize
split_counts = {s: pd.Series([c for _, c in d]).value_counts() for s, d in splits.items()}
split_df = pd.DataFrame(split_counts).fillna(0).astype(int)
split_df['total'] = split_df.sum(axis=1)
split_df = split_df.sort_values('total', ascending=False)

fig, ax = plt.subplots(figsize=(14, 6))
x_pos = np.arange(len(split_df)); w = 0.25
ax.bar(x_pos - w, split_df['train'], w, label='Train', color='#2A9D8F', alpha=0.9)
ax.bar(x_pos,     split_df['val'],   w, label='Val',   color='#E9C46A', alpha=0.9)
ax.bar(x_pos + w, split_df['test'],  w, label='Test',  color='#E76F51', alpha=0.9)
ax.set_xticks(x_pos)
ax.set_xticklabels(split_df.index, rotation=45, ha='right', fontsize=8)
ax.set_ylabel('Images'); ax.set_title('Stratified Split per Class', fontweight='bold')
ax.legend()
plt.tight_layout()
plt.savefig('split_distribution.png', bbox_inches='tight')
plt.show()

print('\nClass-wise split breakdown:')
print(split_df.to_string())

"""---
## 11. 🔄 Augmentation of Minority Classes <a id='11'></a>

**Applied only to training images.** Val and test sets are never augmented.

**Transforms:** Horizontal flip, Vertical flip, Rotation (90°/180°/270°), Brightness (±30%), Contrast (±20%), Saturation (±20%), Zoom crop (±15%).
"""

def augment_image(img):
    # Horizontal flip
    if random.random() > 0.5:
        img = img.transpose(Image.FLIP_LEFT_RIGHT)
    # Vertical flip
    if random.random() > 0.5:
        img = img.transpose(Image.FLIP_TOP_BOTTOM)
    # Rotation
    angle = random.choice([0, 90, 180, 270])
    if angle: img = img.rotate(angle, expand=False)
    # Brightness
    img = ImageEnhance.Brightness(img).enhance(random.uniform(0.7, 1.3))
    # Contrast
    img = ImageEnhance.Contrast(img).enhance(random.uniform(0.8, 1.2))
    # Saturation
    img = ImageEnhance.Color(img).enhance(random.uniform(0.8, 1.2))
    # Zoom (crop center and resize back)
    if random.random() > 0.5:
        w, h = img.size
        zoom = random.uniform(0.85, 1.0)
        left = int(w * (1 - zoom) / 2); top = int(h * (1 - zoom) / 2)
        img = img.crop((left, top, w - left, h - top)).resize((w, h), Image.LANCZOS)
    return img

# Preview on a Sugarcane image
sc_files = [fp for fp, cls in splits['train'] if 'Sugarcane' in cls or 'sugarcane' in cls.lower()]
if sc_files:
    orig = Image.open(sc_files[0]).convert('RGB')
    fig, axes = plt.subplots(1, 6, figsize=(15, 3))
    axes[0].imshow(orig); axes[0].set_title('Original', fontsize=8); axes[0].axis('off')
    for i in range(1, 6):
        axes[i].imshow(augment_image(orig.copy()))
        axes[i].set_title(f'Aug {i}', fontsize=8); axes[i].axis('off')
    plt.suptitle('Augmentation Preview — Sugarcane', fontweight='bold')
    plt.tight_layout()
    plt.savefig('augmentation_preview.png', bbox_inches='tight')
    plt.show()

# Identify minority classes and augment
train_counts = pd.Series([cls for _, cls in splits['train']]).value_counts()
minority_classes = train_counts[train_counts < AUG_THRESHOLD].index.tolist()

print(f'Augmenting classes with < {AUG_THRESHOLD} training images → target {AUG_TARGET}:')
for cls in minority_classes:
    print(f'  {cls}: {train_counts[cls]} → {AUG_TARGET}')

augmented_records = []
for cls in minority_classes:
    cls_files = [(fp, c) for fp, c in splits['train'] if c == cls]
    needed = AUG_TARGET - len(cls_files)
    aug_dir = os.path.join(TEMP_RESIZED, f'{cls}_aug')
    os.makedirs(aug_dir, exist_ok=True)
    generated = 0
    for i in tqdm(range(needed), desc=f'Augmenting {cls}'):
        src_fp, _ = random.choice(cls_files)
        try:
            aug = augment_image(Image.open(src_fp).convert('RGB')).resize(TARGET_SIZE, Image.LANCZOS)
            out = os.path.join(aug_dir, f'aug_{i:04d}_{os.path.basename(src_fp)}')
            aug.save(out, 'JPEG', quality=95)
            augmented_records.append((out, cls)); generated += 1
        except Exception as e:
            print(f'Warning: {e}')
    print(f'  ✅ {cls}: {len(cls_files)} → {len(cls_files) + generated}')

splits['train'].extend(augmented_records)
print(f'\nUpdated training set: {len(splits["train"])} images')

# Before vs after chart
after_counts = pd.Series([cls for _, cls in splits['train']]).value_counts().sort_values(ascending=False)
fig, axes = plt.subplots(1, 2, figsize=(16, 5))
train_counts.sort_values(ascending=False).plot(kind='bar', ax=axes[0], color='#E76F51', edgecolor='white', alpha=0.85)
axes[0].set_title('Before Augmentation (Train)', fontweight='bold')
axes[0].set_xticklabels(axes[0].get_xticklabels(), rotation=45, ha='right', fontsize=7)
after_counts.plot(kind='bar', ax=axes[1], color='#2A9D8F', edgecolor='white', alpha=0.85)
axes[1].set_title('After Augmentation (Train)', fontweight='bold')
axes[1].set_xticklabels(axes[1].get_xticklabels(), rotation=45, ha='right', fontsize=7)
plt.suptitle('Class Distribution: Before vs After Augmentation', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('before_after_augmentation.png', bbox_inches='tight')
plt.show()

"""---
## 12. 💾 Save Final Dataset to Google Drive <a id='12'></a>
"""

# Build final folder structure locally first
print('Building train/val/test folder structure...')
copy_log = {'train': 0, 'val': 0, 'test': 0}

for split_name, data in splits.items():
    for fp, cls in tqdm(data, desc=f'Copying {split_name}'):
        try:
            dest = os.path.join(PROCESSED_PATH, split_name, cls)
            os.makedirs(dest, exist_ok=True)
            shutil.copy2(fp, os.path.join(dest, os.path.basename(fp)))
            copy_log[split_name] += 1
        except Exception as e:
            print(f'Copy error: {e}')

print('\n✅ Local folder structure built:')
for s, c in copy_log.items():
    print(f'   {s:5s}: {c} images')

# Mount Drive and save permanently
from google.colab import drive
drive.mount('/content/drive')

print(f'Saving to Google Drive: {DRIVE_SAVE_PATH}')
if os.path.exists(DRIVE_SAVE_PATH):
    shutil.rmtree(DRIVE_SAVE_PATH)
shutil.copytree(PROCESSED_PATH, DRIVE_SAVE_PATH)
print('✅ Dataset saved to Google Drive!')

# Save manifest CSV
manifest = []
for split_name, data in splits.items():
    for fp, cls in data:
        manifest.append({'split': split_name, 'filepath': fp, 'class': cls,
                         'crop': cls.split('_')[0].replace('__',''),
                         'augmented': 'aug_' in os.path.basename(fp)})
manifest_df = pd.DataFrame(manifest)
manifest_df.to_csv(os.path.join(DRIVE_SAVE_PATH, 'preprocessing_manifest.csv'), index=False)
print(f'✅ Manifest saved: preprocessing_manifest.csv  ({len(manifest_df)} rows)')

"""---
## 13. 📋 Final Verification & Summary <a id='13'></a>
"""

# Leakage check — cross-split MD5 verification
print('Running cross-split leakage check...')

def get_hashes_from_dir(split_path):
    hashes = set()
    for cls in os.listdir(split_path):
        cls_dir = os.path.join(split_path, cls)
        if os.path.isdir(cls_dir):
            for f in os.listdir(cls_dir):
                fp = os.path.join(cls_dir, f)
                try:
                    with open(fp, 'rb') as fh:
                        hashes.add(hashlib.md5(fh.read()).hexdigest())
                except: pass
    return hashes

train_hashes = get_hashes_from_dir(os.path.join(DRIVE_SAVE_PATH, 'train'))
val_hashes   = get_hashes_from_dir(os.path.join(DRIVE_SAVE_PATH, 'val'))
test_hashes  = get_hashes_from_dir(os.path.join(DRIVE_SAVE_PATH, 'test'))

tv_overlap = len(train_hashes & val_hashes)
tt_overlap = len(train_hashes & test_hashes)
vt_overlap = len(val_hashes   & test_hashes)

print(f'   train ∩ val  overlap : {tv_overlap}')
print(f'   train ∩ test overlap : {tt_overlap}')
print(f'   val   ∩ test overlap : {vt_overlap}')

if tv_overlap == 0 and tt_overlap == 0 and vt_overlap == 0:
    print('\n✅ LEAKAGE CHECK PASSED — zero overlap across all splits')
else:
    print('\n⚠️  WARNING — overlap detected, investigate before M3')

# Verify folder structure counts on Drive
print('Verifying final folder structure on Google Drive...\n')
total_verified = 0
for split_name in ['train', 'val', 'test']:
    split_dir = os.path.join(DRIVE_SAVE_PATH, split_name)
    split_total = 0
    print(f'  {split_name}/')
    for cls in sorted(os.listdir(split_dir)):
        count = len(os.listdir(os.path.join(split_dir, cls)))
        split_total += count
        print(f'    {cls}: {count}')
    print(f'  Subtotal: {split_total}\n')
    total_verified += split_total
print(f'Total images verified: {total_verified}')

# Final summary
aug_added = len(augmented_records)
new_train = len(splits['train'])
new_val   = len(splits['val'])
new_test  = len(splits['test'])

print('=' * 62)
print('   ✅ M2 COMPLETE — DATASET FULLY READY FOR M3')
print('=' * 62)
print(f'''
ORIGINAL DATASET
   Raw images          : 13,324
   Exact duplicates    : removed
   Near-duplicates     : removed
   Corrupt files       : 0

PREPROCESSING APPLIED
   Resize              : {TARGET_SIZE} px (LANCZOS)
   Colour space        : RGB (verified)
   Augmented classes   : {minority_classes}
   Images added        : {aug_added}

FINAL SPLIT (stratified, seed={RANDOM_STATE})
   Train               : {new_train} images  (80%)
   Validation          : {new_val} images  (10%)
   Test                : {new_test} images  (10%)
   Leakage check       : PASSED (0 cross-split overlap)

OUTPUT
   Google Drive        : {DRIVE_SAVE_PATH}
   Manifest CSV        : preprocessing_manifest.csv

M3 LOADING — PyTorch
   from torchvision import datasets
   train_ds = datasets.ImageFolder(f"{DRIVE_SAVE_PATH}/train", transform=...)
   val_ds   = datasets.ImageFolder(f"{DRIVE_SAVE_PATH}/val",   transform=...)
   test_ds  = datasets.ImageFolder(f"{DRIVE_SAVE_PATH}/test",  transform=...)

M3 LOADING — TensorFlow/Keras
   tf.keras.utils.image_dataset_from_directory(f"{DRIVE_SAVE_PATH}/train", ...)
''')
print('=' * 62)

"""## 🗑️ Clean Up Dataset Files

This section removes the large dataset files and temporary directories to free up disk space in the Colab environment, as requested. The notebook's code logic remains intact.
"""

import os
import shutil

print('🗑️ Cleaning up large dataset files from Colab environment...')

# Remove the downloaded Kaggle zip file
if os.path.exists('top-agriculture-crop-disease.zip'):
    os.remove('top-agriculture-crop-disease.zip')
    print('   Removed: top-agriculture-crop-disease.zip')

# Remove the unzipped raw dataset directory
if os.path.exists('/content/dataset'):
    shutil.rmtree('/content/dataset')
    print('   Removed: /content/dataset directory')

# Remove the temporary resized images directory
if os.path.exists('/content/resized_temp'):
    shutil.rmtree('/content/resized_temp')
    print('   Removed: /content/resized_temp directory')

# Remove the locally processed directory (before saving to Drive)
if os.path.exists('/content/processed'):
    shutil.rmtree('/content/processed')
    print('   Removed: /content/processed directory')

print('✅ Cleanup complete. Disk space has been freed.')